
[package]
name = "cmasfo-dev"
version = "0.0.31"
edition = "2021"
description = "cmasfo dev dependency"
license = "mit"
documentation = "https://docs.rs/crate/cmasfo-dev/latest"
homepage = "https://github.com/cmasfo"
repository = "https://github.com/cmasfo/cmasfo-dev"

[dependencies]
